const PROBLEM_BANK = {
  'dp': [
    { name: 'Climbing Stairs', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/climbing-stairs/' },
    { name: 'House Robber', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/house-robber/' },
    { name: 'Min Cost Climbing Stairs', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/min-cost-climbing-stairs/' },
    { name: 'Pascal Triangle', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/pascals-triangle/' },
    { name: 'Maximum Subarray', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/maximum-subarray/' },
    { name: 'Coin Change', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/coin-change/' },
    { name: 'Longest Increasing Subsequence', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/longest-increasing-subsequence/' },
    { name: 'Longest Common Subsequence', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/longest-common-subsequence/' },
    { name: 'Unique Paths', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/unique-paths/' },
    { name: 'Jump Game', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/jump-game/' },
    { name: 'Partition Equal Subset Sum', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/partition-equal-subset-sum/' },
    { name: 'DP Knapsack CF', platform: 'Codeforces', difficulty: 'Medium', url: 'https://codeforces.com/problemset/problem/414/B' },
    { name: 'Edit Distance', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/edit-distance/' },
    { name: 'Regular Expression Matching', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/regular-expression-matching/' },
    { name: 'Burst Balloons', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/burst-balloons/' },
    { name: 'Scramble String', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/scramble-string/' },
  ],
  'graphs': [
    { name: 'Find if Path Exists', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/find-if-path-exists-in-graph/' },
    { name: 'Flood Fill', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/flood-fill/' },
    { name: 'Number of Islands', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/number-of-islands/' },
    { name: 'Course Schedule', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/course-schedule/' },
    { name: 'Course Schedule II', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/course-schedule-ii/' },
    { name: 'Clone Graph', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/clone-graph/' },
    { name: 'Rotting Oranges', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/rotting-oranges/' },
    { name: 'Pacific Atlantic Water Flow', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/pacific-atlantic-water-flow/' },
    { name: 'Dijkstra CF', platform: 'Codeforces', difficulty: 'Medium', url: 'https://codeforces.com/problemset/problem/20/C' },
    { name: 'Graph BFS CF', platform: 'Codeforces', difficulty: 'Medium', url: 'https://codeforces.com/problemset/problem/580/C' },
    { name: 'Word Ladder', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/word-ladder/' },
    { name: 'Alien Dictionary', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/alien-dictionary/' },
    { name: 'Critical Connections', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/critical-connections-in-a-network/' },
  ],
  'trees': [
    { name: 'Maximum Depth of Binary Tree', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/' },
    { name: 'Invert Binary Tree', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/invert-binary-tree/' },
    { name: 'Symmetric Tree', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/symmetric-tree/' },
    { name: 'Diameter of Binary Tree', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/diameter-of-binary-tree/' },
    { name: 'Validate Binary Search Tree', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/validate-binary-search-tree/' },
    { name: 'Binary Tree Level Order Traversal', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/binary-tree-level-order-traversal/' },
    { name: 'Lowest Common Ancestor', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/' },
    { name: 'Binary Tree Right Side View', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/binary-tree-right-side-view/' },
    { name: 'Construct Binary Tree from Preorder', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/' },
    { name: 'Binary Tree Maximum Path Sum', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/' },
    { name: 'Serialize and Deserialize Binary Tree', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/' },
    { name: 'Binary Tree Cameras', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/binary-tree-cameras/' },
  ],
  'greedy': [
    { name: 'Assign Cookies', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/assign-cookies/' },
    { name: 'Lemonade Change', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/lemonade-change/' },
    { name: 'Jump Game', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/jump-game/' },
    { name: 'Jump Game II', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/jump-game-ii/' },
    { name: 'Gas Station', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/gas-station/' },
    { name: 'Task Scheduler', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/task-scheduler/' },
    { name: 'Greedy CF Easy', platform: 'Codeforces', difficulty: 'Easy', url: 'https://codeforces.com/problemset/problem/670/C' },
    { name: 'Greedy CF Medium', platform: 'Codeforces', difficulty: 'Medium', url: 'https://codeforces.com/problemset/problem/825/C' },
    { name: 'Candy', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/candy/' },
    { name: 'IPO', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/ipo/' },
  ],
  'binary search': [
    { name: 'Binary Search', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/binary-search/' },
    { name: 'First Bad Version', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/first-bad-version/' },
    { name: 'Search Insert Position', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/search-insert-position/' },
    { name: 'Search in Rotated Sorted Array', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
    { name: 'Find Minimum in Rotated Array', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
    { name: 'Time Based Key Value Store', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/time-based-key-value-store/' },
    { name: 'Koko Eating Bananas', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/koko-eating-bananas/' },
    { name: 'BS CF Medium', platform: 'Codeforces', difficulty: 'Medium', url: 'https://codeforces.com/problemset/problem/760/B' },
    { name: 'Median of Two Sorted Arrays', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/' },
    { name: 'Split Array Largest Sum', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/split-array-largest-sum/' },
  ],
  'two pointers': [
    { name: 'Valid Palindrome', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/valid-palindrome/' },
    { name: 'Merge Sorted Array', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/merge-sorted-array/' },
    { name: 'Two Sum II', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/' },
    { name: 'Container With Most Water', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/container-with-most-water/' },
    { name: '3Sum', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/3sum/' },
    { name: 'Sort Colors', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/sort-colors/' },
    { name: 'Longest Substring Without Repeating', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/' },
    { name: 'Trapping Rain Water', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/trapping-rain-water/' },
    { name: 'Minimum Window Substring', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/minimum-window-substring/' },
  ],
  'strings': [
    { name: 'Valid Anagram', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/valid-anagram/' },
    { name: 'Reverse String', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/reverse-string/' },
    { name: 'First Unique Character', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/first-unique-character-in-a-string/' },
    { name: 'Longest Palindromic Substring', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/longest-palindromic-substring/' },
    { name: 'Group Anagrams', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/group-anagrams/' },
    { name: 'String to Integer atoi', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/string-to-integer-atoi/' },
    { name: 'Decode Ways', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/decode-ways/' },
    { name: 'String CF Easy', platform: 'Codeforces', difficulty: 'Easy', url: 'https://codeforces.com/problemset/problem/432/C' },
    { name: 'Minimum Window Substring', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/minimum-window-substring/' },
    { name: 'Regular Expression Matching', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/regular-expression-matching/' },
  ],
  'math': [
    { name: 'Fizz Buzz', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/fizz-buzz/' },
    { name: 'Count Primes', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/count-primes/' },
    { name: 'Power of Two', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/power-of-two/' },
    { name: 'Reverse Integer', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/reverse-integer/' },
    { name: 'Pow(x,n)', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/powx-n/' },
    { name: 'Excel Sheet Column Number', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/excel-sheet-column-number/' },
    { name: 'Math CF Easy', platform: 'Codeforces', difficulty: 'Easy', url: 'https://codeforces.com/problemset/problem/1/A' },
    { name: 'Math CF Medium', platform: 'Codeforces', difficulty: 'Medium', url: 'https://codeforces.com/problemset/problem/572/B' },
    { name: 'Integer to Roman', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/integer-to-roman/' },
    { name: 'Basic Calculator', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/basic-calculator/' },
  ],
  'dfs and similar': [
    { name: 'Path Sum', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/path-sum/' },
    { name: 'Flood Fill', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/flood-fill/' },
    { name: 'Word Search', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/word-search/' },
    { name: 'Number of Islands', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/number-of-islands/' },
    { name: 'Surrounded Regions', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/surrounded-regions/' },
    { name: 'Permutations', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/permutations/' },
    { name: 'Subsets', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/subsets/' },
    { name: 'DFS CF Medium', platform: 'Codeforces', difficulty: 'Medium', url: 'https://codeforces.com/problemset/problem/580/C' },
    { name: 'N Queens', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/n-queens/' },
    { name: 'Word Search II', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/word-search-ii/' },
  ],
  'data structures': [
    { name: 'Valid Parentheses', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/valid-parentheses/' },
    { name: 'Implement Queue using Stacks', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/implement-queue-using-stacks/' },
    { name: 'Min Stack', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/min-stack/' },
    { name: 'LRU Cache', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/lru-cache/' },
    { name: 'Design HashMap', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/design-hashmap/' },
    { name: 'Implement Trie', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
    { name: 'Find Median from Data Stream', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/find-median-from-data-stream/' },
    { name: 'Serialize Deserialize BST', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/serialize-and-deserialize-bst/' },
  ],
  'sorting': [
    { name: 'Sort Colors', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/sort-colors/' },
    { name: 'Kth Largest Element', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/' },
    { name: 'Merge Intervals', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/merge-intervals/' },
    { name: 'Meeting Rooms II', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/meeting-rooms-ii/' },
    { name: 'Sorting CF Easy', platform: 'Codeforces', difficulty: 'Easy', url: 'https://codeforces.com/problemset/problem/670/C' },
    { name: 'Largest Number', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/largest-number/' },
    { name: 'Count of Smaller Numbers', platform: 'LeetCode', difficulty: 'Hard', url: 'https://leetcode.com/problems/count-of-smaller-numbers-after-self/' },
  ],
  'number theory': [
    { name: 'Count Primes', platform: 'LeetCode', difficulty: 'Easy', url: 'https://leetcode.com/problems/count-primes/' },
    { name: 'GCD CF', platform: 'Codeforces', difficulty: 'Easy', url: 'https://codeforces.com/problemset/problem/75/C' },
    { name: 'NT CF Medium', platform: 'Codeforces', difficulty: 'Medium', url: 'https://codeforces.com/problemset/problem/584/B' },
    { name: 'Ugly Number II', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/ugly-number-ii/' },
    { name: 'NT CF Hard', platform: 'Codeforces', difficulty: 'Hard', url: 'https://codeforces.com/problemset/problem/628/D' },
  ],
  'implementation': [
    { name: 'Impl CF Easy 1', platform: 'Codeforces', difficulty: 'Easy', url: 'https://codeforces.com/problemset/problem/1/A' },
    { name: 'Impl CF Easy 2', platform: 'Codeforces', difficulty: 'Easy', url: 'https://codeforces.com/problemset/problem/4/A' },
    { name: 'Impl CF Medium 1', platform: 'Codeforces', difficulty: 'Medium', url: 'https://codeforces.com/problemset/problem/545/C' },
    { name: 'Impl CF Medium 2', platform: 'Codeforces', difficulty: 'Medium', url: 'https://codeforces.com/problemset/problem/558/C' },
    { name: 'Spiral Matrix', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/spiral-matrix/' },
    { name: 'Game of Life', platform: 'LeetCode', difficulty: 'Medium', url: 'https://leetcode.com/problems/game-of-life/' },
  ],
};

export const getProblemsForDifficulty = (tag, difficulty) => {
    const bank = PROBLEM_BANK[tag];
    if(!bank) {
        return [];
    }
    return bank.filter(p => p.difficulty === difficulty);
};

export const getProblemsForTag = (tag) => {
    return PROBLEM_BANK[tag] || [];
};

export default PROBLEM_BANK;